#!/usr/bin/osascript

set selfPath to POSIX path of ((path to me as text) & "::")
set command to ("exec " & selfPath & "/launcher")

try
	tell application "Finder" to get application file id "com.googlecode.iterm2"
	tell application "iTerm"
		set newWindow to (create window with default profile)
		tell current session of newWindow
			write text command
		end tell
	end tell
on error
	tell application "Terminal"
		activate
		do script with command command
	end tell
end try

